### ISSUE TITLE
Tips & Tricks

### ISSUE THREAD

**Issue by verbose9** [verbose9/superapp-101#4]
## Tips
- Keep Calm(Patience is everything)
- using emojis 🔥😊 in your code make you feel more lightweight and enthusiastic
- don't get surprised
- always think technically

## Tricks
- Don't Repeat Yourself (DRY)
- if you have a less readable code that takes only 2 lines and a more readable code that takes 5 lines, then go for 5 lines of code.
- don't feel inferior to anyone
- don't hesitate in asking (someone who don't answer you is a complete asshole)

**Comment by Jg-07** [comment]
I have done the work u said bro
do check and assign nxt work
